// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF18E6ytXLmRXc2-Ke6PPICEWePnM72_4',
    appId: '1:316856865434:android:0795a2c4bf6c1277ebc523',
    messagingSenderId: '316856865434',
    projectId: 'fruit-hub-b8e28',
    storageBucket: 'fruit-hub-b8e28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCunzzU2CXM0-YJDPf2by0kSOzeZfTgW50',
    appId: '1:316856865434:ios:8babf5e37064fa17ebc523',
    messagingSenderId: '316856865434',
    projectId: 'fruit-hub-b8e28',
    storageBucket: 'fruit-hub-b8e28.firebasestorage.app',
    androidClientId: '316856865434-a1ui0fr97mpal44op6g8ci8a89b7halt.apps.googleusercontent.com',
    iosClientId: '316856865434-9orl4sufr6eecpgfbac1qagd2g5tgfjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCunzzU2CXM0-YJDPf2by0kSOzeZfTgW50',
    appId: '1:316856865434:ios:8babf5e37064fa17ebc523',
    messagingSenderId: '316856865434',
    projectId: 'fruit-hub-b8e28',
    storageBucket: 'fruit-hub-b8e28.firebasestorage.app',
    androidClientId: '316856865434-a1ui0fr97mpal44op6g8ci8a89b7halt.apps.googleusercontent.com',
    iosClientId: '316856865434-9orl4sufr6eecpgfbac1qagd2g5tgfjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsKqa83NMrl3yno38XeY0vBnfuwO5N4Ik',
    appId: '1:316856865434:web:59a91066f41ffe71ebc523',
    messagingSenderId: '316856865434',
    projectId: 'fruit-hub-b8e28',
    authDomain: 'fruit-hub-b8e28.firebaseapp.com',
    storageBucket: 'fruit-hub-b8e28.firebasestorage.app',
    measurementId: 'G-QXHT8WXVE0',
  );
}
